[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "086befff624d461a20b2f13cc272e1d859aca6c2"
lazy = true
libc = "glibc"
os = "linux"

[[eunoia.download]]
sha256 = "6d2a0c74cadcbe6564eefbfc27f8a2b7599eb6c67e17df6c1f04e3f50b6bdeb1"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-x86_64-linux-gnu.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "bf01d8e026c7a7193586e3bdb9fb5e4fec650cf0"
lazy = true
libc = "glibc"
os = "linux"

[[eunoia.download]]
sha256 = "405d206d0940cc5733b8db9c773c84552b538e6f290340a84d09d8861b9a8ee3"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-aarch64-linux-gnu.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "23b2aeca8e1d4f097efc51838a3aa63c5c4c4ac7"
lazy = true
libc = "musl"
os = "linux"

[[eunoia.download]]
sha256 = "7719b6011f32a7ae9c51c39e5676e368e45548347f768e449906acc65acad0b1"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-x86_64-linux-musl.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "39e876d8ce2999dbf1f8ae3aec9f307bcbf2c8e6"
lazy = true
libc = "musl"
os = "linux"

[[eunoia.download]]
sha256 = "8d84b9aba374a4d3c4427999c42434de9479325b3075d9e9202f18d6fe9f4eb8"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-aarch64-linux-musl.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "69f8702537cbc0ad1716cd904cab328002363dce"
lazy = true
os = "macos"

[[eunoia.download]]
sha256 = "4f0deca52457b81c1ad9f6521b13fc9b13db84c24cf93e3eb66fe3451ea9a664"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-x86_64-apple-darwin.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "31604f7880cfc24649cf37fd00eac24a992b22b8"
lazy = true
os = "macos"

[[eunoia.download]]
sha256 = "84ca4e6224df7754409d85c4a3aaa68013576de99f59b51ddfd1ae32768cfd4b"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-aarch64-apple-darwin.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "0a1e30fd51a324fd5901cf73573221eef95fa052"
lazy = true
os = "windows"

[[eunoia.download]]
sha256 = "a06ca3000f47b74fe33891586551d177665cb059dab643662dfb921121063354"
url = "https://github.com/jolars/eunoia/releases/download/v1.5.0/libeunoia_capi-x86_64-w64-mingw32.tar.gz"
