[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "eb7f80cc952f149c6700c34a7639f21c35686c30"
lazy = true
libc = "glibc"
os = "linux"

    [[eunoia.download]]
    sha256 = "ed35feeb638c2f71a93b85da11cafcb82fe7aa55f79fd54d88014dea398285d9"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-x86_64-linux-gnu.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "81a0624f53f1b07fcd39c2aafcfa99ed995e32cc"
lazy = true
libc = "glibc"
os = "linux"

    [[eunoia.download]]
    sha256 = "972479b2c1d564a6d0d9d496ae30e833925245ddda4be0a13d70375ae1d08e65"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-aarch64-linux-gnu.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "b3d13b4dcdcbb2902331731fa8f7c294f1c9eac9"
lazy = true
libc = "musl"
os = "linux"

    [[eunoia.download]]
    sha256 = "714cb650871b5395bbddba723f7aff62dfb75fae5a7bb60720b41ef92f5922d2"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-x86_64-linux-musl.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "422f4280c47b2c96082f76576438fd18d9650463"
lazy = true
libc = "musl"
os = "linux"

    [[eunoia.download]]
    sha256 = "67d74a561e9cc947e68f536832002121c4bb1d5d7477d2f7c9e54e6d8f565f27"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-aarch64-linux-musl.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "23d68dde6006cc631947d8bc43c2c533caf790d2"
lazy = true
os = "macos"

    [[eunoia.download]]
    sha256 = "2b403c296f3d54875090827bfe3d6c1a677386495e195007a62cff500ed63955"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-x86_64-apple-darwin.tar.gz"
[[eunoia]]
arch = "aarch64"
git-tree-sha1 = "4ef2e947256c1c56dccacc31c8fd493efb035608"
lazy = true
os = "macos"

    [[eunoia.download]]
    sha256 = "64392af03673a574841cca7ce6d7fbdc17ef168471fa61ae2c5e0a8393887072"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-aarch64-apple-darwin.tar.gz"
[[eunoia]]
arch = "x86_64"
git-tree-sha1 = "cafeadfc2948d44b4da20ee0cb19e31e374e55c0"
lazy = true
os = "windows"

    [[eunoia.download]]
    sha256 = "e6c36de04ce2da014a1b5214fe67ff9a1ca1ab7bb707e1b85b290770f2e978f6"
    url = "https://github.com/jolars/eunoia/releases/download/v1.3.0/libeunoia_capi-x86_64-w64-mingw32.tar.gz"
