using Documenter
using Eunoia

# Mirror the repo CHANGELOG into the docs sources (generated by release-please;
# guard so a fresh checkout without one still builds).
changelog = joinpath(@__DIR__, "../CHANGELOG.md")
pages = ["Home" => "index.md", "API Reference" => "api.md"]
if isfile(changelog)
  cp(changelog, joinpath(@__DIR__, "src/CHANGELOG.md"); force=true)
  push!(pages, "Changelog" => "CHANGELOG.md")
end

makedocs(
  sitename="Eunoia",
  format=Documenter.HTML(
    assets=["assets/favicon.ico"],
  ),
  modules=[Eunoia],
  checkdocs=:exports,
  pages=pages,
)

deploydocs(
  repo="https://github.com/jolars/Eunoia.jl.git"
)
